// colors
// http://simple.wikipedia.org/wiki/List_of_colors
exports.data = [
    "Amaranth",
    "Amber",
    "Apricot",
    "Aquamarine",
    "Azure",
    "Baby blue",
    "Beige",
    "Black",
    "Blue",
    "Blue-green",
    "Bronze",
    "Brown",
    "Byzantium",
    "Carmine",
    "Cerise",
    "Cerulean",
    "Champagne",
    "Coffee",
    "Copper",
    "Coral",
    "Crimson",
    "Cyan",
    "Electric blue",
    "Erin",
    "Gold",
    "Gray",
    "Green",
    "Harlequin",
    "Indigo",
    "Ivory",
    "Jade",
    "Lavender",
    "Lilac",
    "Lime",
    "Magenta",
    "Maroon",
    "Mauve",
    "Navy blue",
    "Olive",
    "Orange",
    "Orange-red",
    "Peach",
    "Persian blue",
    "Pink",
    "Plum",
    "Prussian blue",
    "Purple",
    "Raspberry",
    "Red",
    "Red-violet",
    "Rose",
    "Salmon",
    "Scarlet",
    "Silver",
    "Taupe",
    "Teal",
    "Turquoise",
    "Violet",
    "Viridian",
    "White",
    "Yellow"
]